experiments:
  - id: 0
    target_column: "Zpopteach"
    other_columns:
      - "Zpopular"
      - "Zextrav"
      - "Zsex"
      - "Ztexp"
    groups_column: "class"
    path: "./Datasets/popular2.sav"
    type: "sav"
  - id: 1
    target_column: "L"
    other_columns:
      - "N"
      - "B"
      - "R"
      - "Ln"
      - "Nn"
      - "Bn"
      - "Rn"
    groups_column: "Environment"
    path: "./Datasets/dataset1reshape.csv"
    type: "csv"
  - id: 2
    target_column: "L120"
    other_columns:
      - "L118"
      - "L121"
      - "L150"
      - "L152"
      - "L153"
      - "L154"
      - "L155"
      - "L156"
      - "L157"
      - "L159"
      - "L160"
      - "L161"
      - "L163"
      - "L165"
      - "L166"
      - "L17"
      - "L18"
      - "L19"
      - "L21"
      - "L30"
      - "L32"
      - "L34"
      - "L36"
      - "L37"
      - "L39"
      - "L43"
      - "L44"
      - "L46"
      - "L89"
      - "L90"
    groups_column: "Environment"
    path: "./Datasets/dataset2reshape.csv"
    type: "csv"
  - id: 3
    target_column: "L1"
    other_columns:
      - "L2"
      - "L3"
      - "L4"
      - "L5"
      - "L6"
      - "L7"
      - "L8"
      - "L9"
      - "L10"
    groups_column: "Environment"
    path: "./Datasets/dataset3reshape.csv"
    type: "csv"
  - id: 4
    target_column: "L1"
    other_columns:
      - "L2"
      - "L3"
      - "L4"
      - "L5"
      - "L6"
      - "L7"
      - "L8"
      - "L9"
      - "L10"
      - "L11"
      - "L12"
      - "L13"
      - "L14"
      - "L15"
    groups_column: "Environment"
    path: "./Datasets/dataset4reshape.csv"
    type: "csv"
  - id: 5
    target_column: "B1"
    other_columns:
      - "B2"
      - "B3"
      - "B4"
      - "B5"
      - "B6"
      - "B7"
      - "B8"
      - "B9"
      - "B10"
      - "B11"
      - "B12"
      - "B13"
      - "B14"
      - "B15"
      - "B16"
      - "B17"
      - "B18"
      - "B19"
      - "B20"
    groups_column: "Environment"
    path: "./Datasets/dataset5reshape.csv"
    type: "csv"
  - id: 6
    target_column: "L1"
    other_columns:
      - "L2"
      - "L3"
      - "L4"
      - "L5"
      - "L6"
      - "L7"
      - "L8"
      - "L9"
      - "L10"
      - "L11"
      - "L12"
      - "L13"
      - "L14"
      - "L15"
      - "L16"
      - "L17"
      - "L18"
      - "L19"
      - "L20"
      - "L21"
      - "L22"
      - "L23"
      - "L24"
      - "L25"
      - "L26"
      - "L27"
      - "L28"
      - "L29"
      - "L30"
      - "L31"
      - "L32"
      - "L33"
      - "L34"
      - "L35"
      - "L36"
      - "L37"
      - "L38"
      - "L39"
      - "L40"
      - "L41"
      - "L42"
      - "L43"
      - "L44"
      - "L45"
      - "L46"
      - "L47"
      - "L48"
      - "L49"
      - "L50"
      - "L51"
      - "L52"
      - "L53"
      - "L54"
      - "L55"
      - "L56"
      - "L57"
      - "L58"
      - "L59"
      - "L60"
    groups_column: "Environment"
    path: "./Datasets/dataset6reshape.csv"
    type: "csv"